---
- name: Update and upgrade apt packages
  hosts: all 
  tasks:
    - name: Update packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        update_cache: yes

    - name: Upgrade packages with apt
      when: ansible_pkg_mgr == 'apt'
      apt:
        upgrade: dist
